/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*

public class Library {
    public boolean someLibraryMethod main() {
        return true;
    }
    public int[] roll (int n){
        Random r = new Random();
        int[] rolls = new int[n];
        for (int i =0; i < n; i++){
            int rNum =r.nextInt(4);
            rolls[i] =rNum + 1;
        }
        return rolls;
    }
    public boolean containsDuplicates (int[] arr){
        for (int i =0; i < arr.length; j++){
            if (i == j) continue;
            if (arr[i] == arr[j]){
                return true;

            }
        }
        return false
    }
}
